<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BarangPendukungSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = [
            [
                'kode_barang' => '1000',
                'nama_barang' => 'JERIGEN 1KG',
                'size' => 'PCS',
                'stock' => 0,
                'kategori' => 'JERIGEN',
                'min_ammount' => 0,
                'stock_akhir' => 967,
                'price' => 3700,
            ],
            [
                'kode_barang' => '1001',
                'nama_barang' => 'JERIGEN 500 ML',
                'size' => 'PCS',
                'stock' => 0,
                'kategori' => 'JERIGEN',
                'min_ammount' => 0,
                'stock_akhir' => 657,
                'price' => 3000,
            ],
            [
                'kode_barang' => '1002',
                'nama_barang' => 'JERIGEN 5 KG',
                'size' => 'PCS',
                'stock' => 0,
                'kategori' => 'JERIGEN',
                'min_ammount' => 0,
                'stock_akhir' => 50,
                'price' => 0,
            ],
            [
                'kode_barang' => '1003',
                'nama_barang' => 'BOTOL 325 ML',
                'size' => 'PCS',
                'stock' => 0,
                'kategori' => 'BOTOL',
                'min_ammount' => 0,
                'stock_akhir' => 199,
                'price' => 1350,
            ],
            [
                'kode_barang' => '1004',
                'nama_barang' => 'BOTOL 125 ML',
                'size' => 'PCS',
                'stock' => 0,
                'kategori' => 'BOTOL',
                'min_ammount' => 0,
                'stock_akhir' => 386,
                'price' => 1031,
            ],
            [
                'kode_barang' => '1005',
                'nama_barang' => 'BOTOL TESTER KECIL',
                'size' => 'PCS',
                'stock' => 0,
                'kategori' => 'BOTOL',
                'min_ammount' => 0,
                'stock_akhir' => 2000,
                'price' => 700,
            ],
            [
                'kode_barang' => '1006',
                'nama_barang' => 'BOTOL TESTER BESAR',
                'size' => 'PCS',
                'stock' => 0,
                'kategori' => 'BOTOL',
                'min_ammount' => 0,
                'stock_akhir' => 290,
                'price' => 900,
            ],
            [
                'kode_barang' => '1007',
                'nama_barang' => 'BOTOL SUPERB 350 G',
                'size' => 'PCS',
                'stock' => 0,
                'kategori' => 'BOTOL',
                'min_ammount' => 0,
                'stock_akhir' => 158,
                'price' => 2500,
            ],
            [
                'kode_barang' => '1008',
                'nama_barang' => 'BOTOL SUPERB 800 G',
                'size' => 'PCS',
                'stock' => 0,
                'kategori' => 'BOTOL',
                'min_ammount' => 0,
                'stock_akhir' => 29,
                'price' => 5900,
            ],
            [
                'kode_barang' => '1009',
                'nama_barang' => 'BOTOL BEEPOLLEN',
                'size' => 'PCS',
                'stock' => 0,
                'kategori' => 'BOTOL',
                'min_ammount' => 0,
                'stock_akhir' => 40,
                'price' => 2000,
            ],
            [
                'kode_barang' => '1010',
                'nama_barang' => 'BOTOL BAWANG BESAR',
                'size' => 'PCS',
                'stock' => 0,
                'kategori' => 'BOTOL',
                'min_ammount' => 0,
                'stock_akhir' => 206,
                'price' => 2500,
            ],
            [
                'kode_barang' => '1011',
                'nama_barang' => 'BOTOL BAWANG KECIL',
                'size' => 'PCS',
                'stock' => 0,
                'kategori' => 'BOTOL',
                'min_ammount' => 0,
                'stock_akhir' => 121,
                'price' => 2000,
            ],
            [
                'kode_barang' => '1012',
                'nama_barang' => 'BOTOL YAMAN BESAR',
                'size' => 'PCS',
                'stock' => 0,
                'kategori' => 'BOTOL',
                'min_ammount' => 0,
                'stock_akhir' => 0,
                'price' => 12000,
            ],
            [
                'kode_barang' => '1013',
                'nama_barang' => 'BOTOL YAMAN KECIL',
                'size' => 'PCS',
                'stock' => 0,
                'kategori' => 'BOTOL',
                'min_ammount' => 0,
                'stock_akhir' => 20,
                'price' => 10000,
            ],
            [
                'kode_barang' => '1014',
                'nama_barang' => 'SENDOK KAYU',
                'size' => 'PCS',
                'stock' => 0,
                'kategori' => 'SENDOK',
                'min_ammount' => 0,
                'stock_akhir' => 600,
                'price' => 2100,
            ],
            [
                'kode_barang' => '1015',
                'nama_barang' => 'SENDOK KAYU TIPIS',
                'size' => 'PCS',
                'stock' => 0,
                'kategori' => 'SENDOK',
                'min_ammount' => 0,
                'stock_akhir' => 300,
                'price' => 540,
            ],
            [
                'kode_barang' => '1016',
                'nama_barang' => 'ADUKAN KAYU',
                'size' => 'PCS',
                'stock' => 0,
                'kategori' => 'SENDOK',
                'min_ammount' => 0,
                'stock_akhir' => 200,
                'price' => 2450,
            ],
            [
                'kode_barang' => '1017',
                'nama_barang' => 'SENDOK PLASTIK',
                'size' => 'PCS',
                'stock' => 0,
                'kategori' => 'SENDOK',
                'min_ammount' => 0,
                'stock_akhir' => 0,
                'price' => 28000,
            ],
            [
                'kode_barang' => '1018',
                'nama_barang' => 'ISOLASI PUTIH',
                'size' => 'PCS',
                'stock' => 0,
                'kategori' => 'ISOLASI',
                'min_ammount' => 0,
                'stock_akhir' => 36,
                'price' => '8700.00',
            ],
            [
                'kode_barang' => '1019',
                'nama_barang' => 'ISOLASI COKLAT',
                'size' => 'PCS',
                'stock' => 0,
                'kategori' => 'ISOLASI',
                'min_ammount' => 0,
                'stock_akhir' => 36,
                'price' => 8700,
            ],
            [
                'kode_barang' => '1020',
                'nama_barang' => 'SOLASI FRAGILE',
                'size' => 'PCS',
                'stock' => 0,
                'kategori' => 'ISOLASI',
                'min_ammount' => 0,
                'stock_akhir' => 11,
                'price' => 8500,
            ],
            [
                'kode_barang' => '1021',
                'nama_barang' => 'KARDUS BESAR',
                'size' => 'PCS',
                'stock' => 0,
                'kategori' => 'KARDUS',
                'min_ammount' => 0,
                'stock_akhir' => 9,
                'price' => 12000,
            ],
            [
                'kode_barang' => '1022',
                'nama_barang' => 'KARDUS SEDANG',
                'size' => 'PCS',
                'stock' => 0,
                'kategori' => 'KARDUS',
                'min_ammount' => 0,
                'stock_akhir' => 16,
                'price' => 3500,
            ],
            [
                'kode_barang' => '1023',
                'nama_barang' => 'KARDUS MADU',
                'size' => 'PCS',
                'stock' => 0,
                'kategori' => 'KARDUS',
                'min_ammount' => 0,
                'stock_akhir' => 1820,
                'price' => 3000,
            ],
            [
                'kode_barang' => '1024',
                'nama_barang' => 'KARDUS HAMPERS KACA MINI',
                'size' => 'PCS',
                'stock' => 0,
                'kategori' => 'KARDUS',
                'min_ammount' => 0,
                'stock_akhir' => 23,
                'price' => 0,
            ],
            [
                'kode_barang' => '1025',
                'nama_barang' => 'KARDUS HAMPERS EKSLUSIF',
                'size' => 'PCS',
                'stock' => 0,
                'kategori' => 'KARDUS',
                'min_ammount' => 0,
                'stock_akhir' => 32,
                'price' => 40000,
            ],
            [
                'kode_barang' => '1026',
                'nama_barang' => 'KARDUS HAMPERS PREMIUM',
                'size' => 'PCS',
                'stock' => 0,
                'kategori' => 'KARDUS',
                'min_ammount' => 0,
                'stock_akhir' => 5,
                'price' => 4500,
            ],
            [
                'kode_barang' => '1027',
                'nama_barang' => 'KARDUS HAMPERS MTP COKLAT',
                'size' => 'PCS',
                'stock' => 0,
                'kategori' => 'KARDUS',
                'min_ammount' => 0,
                'stock_akhir' => 7,
                'price' => 1335,
            ],
            [
                'kode_barang' => '1028',
                'nama_barang' => 'KARDUS HAMPERS HAPPINESS',
                'size' => 'PCS',
                'stock' => 0,
                'kategori' => 'KARDUS',
                'min_ammount' => 0,
                'stock_akhir' => 38,
                'price' => 3000,
            ],
            [
                'kode_barang' => '1029',
                'nama_barang' => 'BUBBLE WRAP',
                'size' => 'PCS',
                'stock' => 0,
                'kategori' => 'BUBBLE WRAP',
                'min_ammount' => 0,
                'stock_akhir' => 8,
                'price' => 1500,
            ],
            [
                'kode_barang' => '1030',
                'nama_barang' => 'PROPOLIS',
                'size' => 'PCS',
                'stock' => 0,
                'kategori' => 'PROPOLIS',
                'min_ammount' => 0,
                'stock_akhir' => 0,
                'price' => 50000,
            ],
            [
                'kode_barang' => '1031',
                'nama_barang' => 'ROYAL JELLY',
                'size' => 'PCS',
                'stock' => 0,
                'kategori' => 'PCS',
                'min_ammount' => 0,
                'stock_akhir' => 2,
                'price' => 800000,
            ],
            [
                'kode_barang' => '1032',
                'nama_barang' => 'KERTAS A4',
                'size' => 'PCS',
                'stock' => 0,
                'kategori' => 'KERTAS',
                'min_ammount' => 0,
                'stock_akhir' => 3,
                'price' => 50000,
            ],
            [
                'kode_barang' => '1033',
                'nama_barang' => 'POUCH BESAR',
                'size' => 'PCS',
                'stock' => 0,
                'kategori' => 'POUCH',
                'min_ammount' => 0,
                'stock_akhir' => 350,
                'price' => 766,
            ],
            [
                'kode_barang' => '1034',
                'nama_barang' => 'POUCH KECIL',
                'size' => 'PCS',
                'stock' => 0,
                'kategori' => 'POUCH',
                'min_ammount' => 0,
                'stock_akhir' => 300,
                'price' => 370,
            ],
            [
                'kode_barang' => '1035',
                'nama_barang' => 'PLASTIK SHRINK 9',
                'size' => 'ROLL',
                'stock' => 0,
                'kategori' => 'PLASTIK',
                'min_ammount' => 0,
                'stock_akhir' => 4,
                'price' => 78000,
            ],
            [
                'kode_barang' => '1036',
                'nama_barang' => 'PLASTIK SHRINK 10 ',
                'size' => 'ROLL',
                'stock' => 0,
                'kategori' => 'PLASTIK',
                'min_ammount' => 0,
                'stock_akhir' => 0,
                'price' => 88000,
            ],
            [
                'kode_barang' => '1037',
                'nama_barang' => 'PLASTIK SHRINK 11',
                'size' => 'ROLL',
                'stock' => 0,
                'kategori' => 'PLASTIK',
                'min_ammount' => 0,
                'stock_akhir' => 4,
                'price' => 78000,
            ],
            [
                'kode_barang' => '1038',
                'nama_barang' => 'PLASTIK SHRINK 16',
                'size' => 'ROLL',
                'stock' => 0,
                'kategori' => 'PLASTIK',
                'min_ammount' => 0,
                'stock_akhir' => 4,
                'price' => 78000,
            ],
            [
                'kode_barang' => '1039',
                'nama_barang' => 'PLASTIK SHRINK 19',
                'size' => 'ROLL',
                'stock' => 0,
                'kategori' => 'PLASTIK',
                'min_ammount' => 0,
                'stock_akhir' => 5,
                'price' => 85500,
            ],
            [
                'kode_barang' => '1040',
                'nama_barang' => 'PLASATIK SHRINK 30',
                'size' => 'ROLL',
                'stock' => 0,
                'kategori' => 'PLASTIK',
                'min_ammount' => 0,
                'stock_akhir' => 1,
                'price' => 0,
            ],
            [
                'kode_barang' => '1041',
                'nama_barang' => 'PLASTIK SHRINK 40',
                'size' => 'ROLL',
                'stock' => 0,
                'kategori' => 'PLASTIK',
                'min_ammount' => 0,
                'stock_akhir' => 1,
                'price' => 0,
            ],
            [
                'kode_barang' => '1042',
                'nama_barang' => 'BEE POLLEN JAGUNG',
                'size' => 'KG',
                'stock' => 0,
                'kategori' => 'BEE POLLEN ',
                'min_ammount' => 0,
                'stock_akhir' => 3,
                'price' => 80000,
            ],
            [
                'kode_barang' => '1043',
                'nama_barang' => 'BEE POLLEN MULTI',
                'size' => 'KG',
                'stock' => 0,
                'kategori' => 'BEE POLLEN ',
                'min_ammount' => 0,
                'stock_akhir' => 0,
                'price' => 135000,
            ],
            [
                'kode_barang' => '1044',
                'nama_barang' => 'ZURIAT',
                'size' => 'KG',
                'stock' => 0,
                'kategori' => 'BEE POLLEN ',
                'min_ammount' => 0,
                'stock_akhir' => 7,
                'price' => 60000,
            ],
            [
                'kode_barang' => '1045',
                'nama_barang' => 'QHUSTUL HINDI',
                'size' => 'KG',
                'stock' => 0,
                'kategori' => 'BEE POLLEN ',
                'min_ammount' => 0,
                'stock_akhir' => 1,
                'price' => 0,
            ],
            [
                'kode_barang' => '1046',
                'nama_barang' => 'CHIA SEED',
                'size' => 'KG',
                'stock' => 0,
                'kategori' => 'BEE POLLEN ',
                'min_ammount' => 0,
                'stock_akhir' => 10,
                'price' => 77000,
            ],
            [
                'kode_barang' => '1047',
                'nama_barang' => 'HIMALAYA SALT',
                'size' => 'KG',
                'stock' => 0,
                'kategori' => 'BEE POLLEN ',
                'min_ammount' => 0,
                'stock_akhir' => 1,
                'price' => 20000,
            ],
            [
                'kode_barang' => '1048',
                'nama_barang' => 'KRESEK MERAH BESAR',
                'size' => 'PAX',
                'stock' => 0,
                'kategori' => 'KRESEK',
                'min_ammount' => 0,
                'stock_akhir' => 0,
                'price' => 12000,
            ],
            [
                'kode_barang' => '1049',
                'nama_barang' => 'KRESEK HITAM BESAR',
                'size' => 'PAX',
                'stock' => 0,
                'kategori' => 'KRESEK',
                'min_ammount' => 0,
                'stock_akhir' => 0,
                'price' => 12000,
            ],
            [
                'kode_barang' => '1050',
                'nama_barang' => 'KRESEK HITAM SEDANG',
                'size' => 'PAX',
                'stock' => 0,
                'kategori' => 'KRESEK',
                'min_ammount' => 0,
                'stock_akhir' => 0,
                'price' => 6000,
            ],
            [
                'kode_barang' => '1051',
                'nama_barang' => 'KRESEK HITAM KECIL',
                'size' => 'PAX',
                'stock' => 0,
                'kategori' => 'KRESEK',
                'min_ammount' => 0,
                'stock_akhir' => 0,
                'price' => 6000,
            ],
            [
                'kode_barang' => '1052',
                'nama_barang' => 'TAS SM KUNING KECIL',
                'size' => 'PCS',
                'stock' => 0,
                'kategori' => 'TAS',
                'min_ammount' => 0,
                'stock_akhir' => 0,
                'price' => 1590,
            ],
            [
                'kode_barang' => '1053',
                'nama_barang' => 'TAS SM KUNING BESAR',
                'size' => 'PCS',
                'stock' => 0,
                'kategori' => 'TAS',
                'min_ammount' => 0,
                'stock_akhir' => 0,
                'price' => 2450,
            ],
            [
                'kode_barang' => '1054',
                'nama_barang' => 'BOTOL KACA 100ml',
                'size' => 'PCS',
                'stock' => 0,
                'kategori' => 'BOTOL',
                'min_ammount' => 0,
                'stock_akhir' => 59,
                'price' => 0,
            ],
            [
                'kode_barang' => '1055',
                'nama_barang' => 'BOTOL KACA 280ml',
                'size' => 'PCS',
                'stock' => 0,
                'kategori' => 'BOTOL',
                'min_ammount' => 0,
                'stock_akhir' => 112,
                'price' => 0,
            ],
            [
                'kode_barang' => '1056',
                'nama_barang' => 'BOX PREMIUM HONEY',
                'size' => 'PCS',
                'stock' => 0,
                'kategori' => 'BOX',
                'min_ammount' => 0,
                'stock_akhir' => 171,
                'price' => 0,
            ],
            [
                'kode_barang' => '1057',
                'nama_barang' => 'BOX SUPER HONEY',
                'size' => 'PCS',
                'stock' => 0,
                'kategori' => 'BOX',
                'min_ammount' => 0,
                'stock_akhir' => 229,
                'price' => 0,
            ],
            [
                'kode_barang' => '1058',
                'nama_barang' => 'BOX RAW HONEY',
                'size' => 'PCS',
                'stock' => 0,
                'kategori' => 'BOX',
                'min_ammount' => 0,
                'stock_akhir' => 200,
                'price' => 0,
            ],
            [
                'kode_barang' => '1059',
                'nama_barang' => 'BOX MINI HONEY',
                'size' => 'PCS',
                'stock' => 0,
                'kategori' => 'BOX',
                'min_ammount' => 0,
                'stock_akhir' => 288,
                'price' => 0,
            ],
            [
                'kode_barang' => '1060',
                'nama_barang' => 'TERMAL',
                'size' => 'PCS',
                'stock' => 0,
                'kategori' => 'TERMAL',
                'min_ammount' => 0,
                'stock_akhir' => 13,
                'price' => 150,
            ],
            [
                'kode_barang' => '1061',
                'nama_barang' => 'BOTOL ROYAL JELLY',
                'size' => 'PCS',
                'stock' => 0,
                'kategori' => 'BOTOL',
                'min_ammount' => 0,
                'stock_akhir' => 80,
                'price' => 0,
            ],
            [
                'kode_barang' => '1062',
                'nama_barang' => 'BOTOL NAT 100ml',
                'size' => 'PCS',
                'stock' => 0,
                'kategori' => 'BOTOL',
                'min_ammount' => 0,
                'stock_akhir' => 392,
                'price' => 0,
            ],
            [
                'kode_barang' => '1063',
                'nama_barang' => 'BOTOL LIMAS SEGI 5',
                'size' => 'PCS',
                'stock' => 0,
                'kategori' => 'BOTOL',
                'min_ammount' => 0,
                'stock_akhir' => 40,
                'price' => 0,
            ],
            [
                'kode_barang' => '1064',
                'nama_barang' => 'BOTOL MUESLI 1300ml ',
                'size' => 'PCS',
                'stock' => 0,
                'kategori' => 'BOTOL',
                'min_ammount' => 0,
                'stock_akhir' => 32,
                'price' => 0,
            ],
            [
                'kode_barang' => '1065',
                'nama_barang' => 'BOX 14 IN 1',
                'size' => 'PCS',
                'stock' => 0,
                'kategori' => 'BOX',
                'min_ammount' => 0,
                'stock_akhir' => 34,
                'price' => 0,
            ],
            [
                'kode_barang' => '1066',
                'nama_barang' => 'BOX 8 IN 1',
                'size' => 'PCS',
                'stock' => 0,
                'kategori' => 'BOX',
                'min_ammount' => 0,
                'stock_akhir' => 12,
                'price' => 0,
            ],
            [
                'kode_barang' => '1067',
                'nama_barang' => 'KERDUS MADU BEST HONEY',
                'size' => 'PCS',
                'stock' => 0,
                'kategori' => 'KERDUS',
                'min_ammount' => 0,
                'stock_akhir' => 1350,
                'price' => 0,
            ],
            [
                'kode_barang' => '1068',
                'nama_barang' => 'SENDOK BEST HONEY',
                'size' => 'PCS',
                'stock' => 0,
                'kategori' => 'SENDOK',
                'min_ammount' => 0,
                'stock_akhir' => 200,
                'price' => 0,
            ],
            [
                'kode_barang' => '1069',
                'nama_barang' => 'SENDOK PREMIUM',
                'size' => 'PCS',
                'stock' => 0,
                'kategori' => 'SENDOK',
                'min_ammount' => 0,
                'stock_akhir' => 0,
                'price' => 0,
            ],
            [
                'kode_barang' => '1070',
                'nama_barang' => 'botol kale 250ml',
                'size' => 'PCS',
                'stock' => 0,
                'kategori' => 'BOTOL',
                'min_ammount' => 0,
                'stock_akhir' => 0,
                'price' => 0,
            ],
            [
                'kode_barang' => '1071',
                'nama_barang' => 'botol kale 500gr',
                'size' => 'PCS',
                'stock' => 0,
                'kategori' => 'BOTOL',
                'min_ammount' => 0,
                'stock_akhir' => 92,
                'price' => 0,
            ],
            [
                'kode_barang' => '1072',
                'nama_barang' => 'botol oval 250ml',
                'size' => 'PCS',
                'stock' => 0,
                'kategori' => 'BOTOL',
                'min_ammount' => 0,
                'stock_akhir' => 20,
                'price' => 0,
            ],
            [
                'kode_barang' => '1073',
                'nama_barang' => 'kerdus sari lemon',
                'size' => 'PCS',
                'stock' => 0,
                'kategori' => 'BOTOL',
                'min_ammount' => 0,
                'stock_akhir' => 86,
                'price' => 0,
            ],
        ];
        DB::table('barang_pendukungs')->insert($data);
    }
}
