<?php

namespace Database\Seeders;

use App\Models\ProdukJadi;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProdukJadiSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        $data = [
            [
                'kode_barang' => '111',
                'nama_barang' => 'MADU MULTIFLORA',
                'size' => '1000',
                'stock' => 0,
                'kategori' => '1kg',
                'stock_akhir' => 134,
                'harga_ecer' => 99000,
                'harga_rs' => 88000,
                'harga_mkl' => 75000,
                'harga_ds' => 80000,
            ],
            [
                'kode_barang' => '112',
                'nama_barang' => 'MADU RANDU',
                'size' => '1000',
                'stock' => 0,
                'kategori' => '1kg',
                'stock_akhir' => 0,
                'harga_ecer' => 130000,
                'harga_rs' => 130000,
                'harga_mkl' => 115000,
                'harga_ds' => 105000,
            ],
            [
                'kode_barang' => '113',
                'nama_barang' => 'MADU KOPI',
                'size' => '1000',
                'stock' => 0,
                'kategori' => '1kg',
                'stock_akhir' => 21,
                'harga_ecer' => 125000,
                'harga_rs' => 107000,
                'harga_mkl' => 100000,
                'harga_ds' => 102000,
            ],
            [
                'kode_barang' => '114',
                'nama_barang' => 'MADU DURIAN',
                'size' => '1000',
                'stock' => 0,
                'kategori' => '1kg',
                'stock_akhir' => 13,
                'harga_ecer' => 126000,
                'harga_rs' => 112000,
                'harga_mkl' => 99000,
                'harga_ds' => 108000,
            ],
            [
                'kode_barang' => '115',
                'nama_barang' => 'MADU KELENGKENG',
                'size' => '1000',
                'stock' => 0,
                'kategori' => '1kg',
                'stock_akhir' => 0,
                'harga_ecer' => 124000,
                'harga_rs' => 124000.00,
                'harga_mkl' => 107000.00,
                'harga_ds' => 97000.00,
            ],
            [
                'kode_barang' => '116',
                'nama_barang' => 'MADU KALIANDRA',
                'size' => '1000',
                'stock' => 0,
                'kategori' => '1kg',
                'stock_akhir' => 36,
                'harga_ecer' => 128000,
                'harga_rs' => 110000,
                'harga_mkl' => 98000,
                'harga_ds' => 98000,
            ],
            [
                'kode_barang' => '117',
                'nama_barang' => 'MADU RAMBUTAN',
                'size' => '1000',
                'stock' => 0,
                'kategori' => '1kg',
                'stock_akhir' => 19,
                'harga_ecer' => 124000,
                'harga_rs' => 107000,
                'harga_mkl' => 97000,
                'harga_ds' => 96000,
            ],
            [
                'kode_barang' => '118',
                'nama_barang' => 'MADU MANGGA',
                'size' => '1000',
                'stock' => 0,
                'kategori' => '1kg',
                'stock_akhir' => 7,
                'harga_ecer' => 128000,
                'harga_rs' => 110000,
                'harga_mkl' => 98000,
                'harga_ds' => 98000,
            ],
            [
                'kode_barang' => '119',
                'nama_barang' => 'MADU KARET',
                'size' => '1000',
                'stock' => 0,
                'kategori' => '1kg',
                'stock_akhir' => 15,
                'harga_ecer' => 118000,
                'harga_rs' => 98000,
                'harga_mkl' => 96000,
                'harga_ds' => 93000,
            ],
            [
                'kode_barang' => '120',
                'nama_barang' => 'MADU SONOKELING',
                'size' => '1000',
                'stock' => 0,
                'kategori' => '1kg',
                'stock_akhir' => 16,
                'harga_ecer' => 117000,
                'harga_rs' => 102000,
                'harga_mkl' => 95000,
                'harga_ds' => 97000,
            ],
            [
                'kode_barang' => '121',
                'nama_barang' => 'MADU HUTAN LIAR',
                'size' => '1000',
                'stock' => 0,
                'kategori' => '1kg',
                'stock_akhir' => 16,
                'harga_ecer' => 150000,
                'harga_rs' => 125000,
                'harga_mkl' => 105000,
                'harga_ds' => 115000,
            ],
            [
                'kode_barang' => '122',
                'nama_barang' => 'MADU HUTAN GUNG',
                'size' => '1000',
                'stock' => 0,
                'kategori' => '1kg',
                'stock_akhir' => 9,
                'harga_ecer' => 160000,
                'harga_rs' => 130000,
                'harga_mkl' => 105000,
                'harga_ds' => 120000,
            ],
            [
                'kode_barang' => '123',
                'nama_barang' => 'MADU JAMBI',
                'size' => '1000',
                'stock' => 0,
                'kategori' => '1kg',
                'stock_akhir' => 7,
                'harga_ecer' => 110000,
                'harga_rs' => 100000,
                'harga_mkl' => 85000,
                'harga_ds' => 90000,
            ],
            [
                'kode_barang' => '124',
                'nama_barang' => 'MADU SUMATERA',
                'size' => '1000',
                'stock' => 0,
                'kategori' => '1kg',
                'stock_akhir' => 17,
                'harga_ecer' => 120000,
                'harga_rs' => 100000,
                'harga_mkl' => 85000,
                'harga_ds' => 90000,
            ],
            [
                'kode_barang' => '125',
                'nama_barang' => 'MADU RIAU',
                'size' => '1000',
                'stock' => 0,
                'kategori' => '1kg',
                'stock_akhir' => 11,
                'harga_ecer' => 120000.00,
                'harga_rs' => 110000,
                'harga_mkl' => 90000,
                'harga_ds' => 100000,
            ],
            [
                'kode_barang' => '126',
                'nama_barang' => 'MADU BANGKA',
                'size' => '1000',
                'stock' => 0,
                'kategori' => '1kg',
                'stock_akhir' => 8,
                'harga_ecer' => 120000,
                'harga_rs' => 110000,
                'harga_mkl' => 90000,
                'harga_ds' => 100000,
            ],
            [
                'kode_barang' => '127',
                'nama_barang' => 'MADU FLORES',
                'size' => '1000',
                'stock' => 0,
                'kategori' => '1kg',
                'stock_akhir' => 13,
                'harga_ecer' => 145000,
                'harga_rs' => 127000,
                'harga_mkl' => 105000,
                'harga_ds' => 122000,
            ],
            [
                'kode_barang' => '128',
                'nama_barang' => 'MADU SUMBAWA',
                'size' => '1000',
                'stock' => 0,
                'kategori' => '1kg',
                'stock_akhir' => 13,
                'harga_ecer' => 150000,
                'harga_rs' => 135000,
                'harga_mkl' => 120000,
                'harga_ds' => 130000,
            ],
            [
                'kode_barang' => '129',
                'nama_barang' => 'MADU AKASIA',
                'size' => '1000',
                'stock' => 0,
                'kategori' => '1kg',
                'stock_akhir' => 18,
                'harga_ecer' => 150000,
                'harga_rs' => 125000,
                'harga_mkl' => 105000,
                'harga_ds' => 115000,
            ],
            [
                'kode_barang' => '130',
                'nama_barang' => 'MADU KLANCENG LEAVYCEPS',
                'size' => '1000',
                'stock' => 0,
                'kategori' => '1kg',
                'stock_akhir' => 14,
                'harga_ecer' => 250000,
                'harga_rs' => 225000,
                'harga_mkl' => 210000,
                'harga_ds' => 215000,
            ],
            [
                'kode_barang' => '131',
                'nama_barang' => 'MADU KLANCENG ITAMA',
                'size' => '1000',
                'stock' => 0,
                'kategori' => '1kg',
                'stock_akhir' => 11,
                'harga_ecer' => 220000,
                'harga_rs' => 200000,
                'harga_mkl' => 190000,
                'harga_ds' => 195000,
            ],
            [
                'kode_barang' => '132',
                'nama_barang' => 'MADU KLANCENG BIROI',
                'size' => '1000',
                'stock' => 0,
                'kategori' => '1kg',
                'stock_akhir' => 13,
                'harga_ecer' => 240000,
                'harga_rs' => 220000,
                'harga_mkl' => 200000,
                'harga_ds' => 215000,
            ],
            [
                'kode_barang' => '133',
                'nama_barang' => 'MADU KLANCENG BAMBU',
                'size' => '1000',
                'stock' => 0,
                'kategori' => '1kg',
                'stock_akhir' => 11,
                'harga_ecer' => 210000,
                'harga_rs' => 180000,
                'harga_mkl' => 175000,
                'harga_ds' => 175000,
            ],
            [
                'kode_barang' => '134',
                'nama_barang' => 'MADU KLANCENG MAUNI',
                'size' => '1000',
                'stock' => 0,
                'kategori' => '1kg',
                'stock_akhir' => 9,
                'harga_ecer' => 190000,
                'harga_rs' => 175000,
                'harga_mkl' => 170000,
                'harga_ds' => 170000,
            ],
            [
                'kode_barang' => '135',
                'nama_barang' => 'MADU PAHIT MAHONI',
                'size' => '1000',
                'stock' => 0,
                'kategori' => '1kg',
                'stock_akhir' => 5,
                'harga_ecer' => 120000,
                'harga_rs' => 100000,
                'harga_mkl' => 85000,
                'harga_ds' => 90000,
            ],
            [
                'kode_barang' => '136',
                'nama_barang' => 'MADU PAHIT JAMBI',
                'size' => '1000',
                'stock' => 0,
                'kategori' => '1kg',
                'stock_akhir' => 20,
                'harga_ecer' => 125000,
                'harga_rs' => 105000,
                'harga_mkl' => 95000,
                'harga_ds' => 95000,
            ],
            [
                'kode_barang' => '211',
                'nama_barang' => 'MADU MULTIFLORA',
                'size' => '500',
                'stock' => 0,
                'kategori' => '500ml',
                'stock_akhir' => 30,
                'harga_ecer' => 73000,
                'harga_rs' => 62000,
                'harga_mkl' => 56000,
                'harga_ds' => 50000,
            ],
            [
                'kode_barang' => '212',
                'nama_barang' => 'MADU RANDU',
                'size' => '500',
                'stock' => 0,
                'kategori' => '500ml',
                'stock_akhir' => 16,
                'harga_ecer' => 99000,
                'harga_rs' => 70000,
                'harga_mkl' => 65000,
                'harga_ds' => 74000,
            ],
            [
                'kode_barang' => '213',
                'nama_barang' => 'MADU KOPI',
                'size' => '500',
                'stock' => 0,
                'kategori' => '500ml',
                'stock_akhir' => 10,
                'harga_ecer' => 95000,
                'harga_rs' => 75000,
                'harga_mkl' => 70000,
                'harga_ds' => 72000,
            ],
            [
                'kode_barang' => '214',
                'nama_barang' => 'MADU DURIAN',
                'size' => '500',
                'stock' => 0,
                'kategori' => '500ml',
                'stock_akhir' => 15,
                'harga_ecer' => 90000,
                'harga_rs' => 78000,
                'harga_mkl' => 73000,
                'harga_ds' => 68000,
            ],
            [
                'kode_barang' => '215',
                'nama_barang' => 'MADU KELENGKENG',
                'size' => '500',
                'stock' => 0,
                'kategori' => '500ml',
                'stock_akhir' => 21,
                'harga_ecer' => '92000.00',
                'harga_rs' => '80000.00',
                'harga_mkl' => '74000.00',
                'harga_ds' => '70000.00',
            ],
            [
                'kode_barang' => '216',
                'nama_barang' => 'MADU KALIANDRA',
                'size' => '500',
                'stock' => 0,
                'kategori' => '500ml',
                'stock_akhir' => 19,
                'harga_ecer' => '95000.00',
                'harga_rs' => '83000.00',
                'harga_mkl' => '75000.00',
                'harga_ds' => '72000.00',
            ],
            [
                'kode_barang' => '217',
                'nama_barang' => 'MADU RAMBUTAN',
                'size' => '500',
                'stock' => 0,
                'kategori' => '500ml',
                'stock_akhir' => 11,
                'harga_ecer' => '94000.00',
                'harga_rs' => '80000.00',
                'harga_mkl' => '74000.00',
                'harga_ds' => '74000.00',
            ],
            [
                'kode_barang' => '218',
                'nama_barang' => 'MADU MANGGA',
                'size' => '500',
                'stock' => 0,
                'kategori' => '500ml',
                'stock_akhir' => 15,
                'harga_ecer' => '97000.00',
                'harga_rs' => '83000.00',
                'harga_mkl' => '75000.00',
                'harga_ds' => '72000.00',
            ],
            [
                'kode_barang' => '219',
                'nama_barang' => 'MADU KARET',
                'size' => '500',
                'stock' => 0,
                'kategori' => '500ml',
                'stock_akhir' => 9,
                'harga_ecer' => '85000.00',
                'harga_rs' => '70000.00',
                'harga_mkl' => '65000.00',
                'harga_ds' => '65000.00',
            ],
            [
                'kode_barang' => '220',
                'nama_barang' => 'MADU SONOKELING',
                'size' => '500',
                'stock' => 0,
                'kategori' => '500ml',
                'stock_akhir' => 22,
                'harga_ecer' => '90000.00',
                'harga_rs' => '74000.00',
                'harga_mkl' => '68000.00',
                'harga_ds' => '67000.00',
            ],
            [
                'kode_barang' => '311',
                'nama_barang' => 'MADU MULTIFLORA',
                'size' => '325',
                'stock' => 0,
                'kategori' => '325ml',
                'stock_akhir' => 31,
                'harga_ecer' => '54000.00',
                'harga_rs' => '45000.00',
                'harga_mkl' => '45000.00',
                'harga_ds' => '38000.00',
            ],
            [
                'kode_barang' => '312',
                'nama_barang' => 'MADU RANDU',
                'size' => '325',
                'stock' => 0,
                'kategori' => '325ml',
                'stock_akhir' => 23,
                'harga_ecer' => '68000.00',
                'harga_rs' => '48000.00',
                'harga_mkl' => '48000.00',
                'harga_ds' => '52000.00',
            ],
            [
                'kode_barang' => '313',
                'nama_barang' => 'MADU KOPI',
                'size' => '325',
                'stock' => 0,
                'kategori' => '325ml',
                'stock_akhir' => 29,
                'harga_ecer' => '63000.00',
                'harga_rs' => '52000.00',
                'harga_mkl' => '47000.00',
                'harga_ds' => '48000.00',
            ],
            [
                'kode_barang' => '314',
                'nama_barang' => 'MADU DURIAN',
                'size' => '325',
                'stock' => 0,
                'kategori' => '325ml',
                'stock_akhir' => 26,
                'harga_ecer' => '66000.00',
                'harga_rs' => '53000.00',
                'harga_mkl' => '48000.00',
                'harga_ds' => '50000.00',
            ],
            [
                'kode_barang' => '315',
                'nama_barang' => 'MADU KELENGKENG',
                'size' => '325',
                'stock' => 0,
                'kategori' => '325ml',
                'stock_akhir' => 36,
                'harga_ecer' => '65000.00',
                'harga_rs' => '55000.00',
                'harga_mkl' => '51000.00',
                'harga_ds' => '48000.00',
            ],
            [
                'kode_barang' => '316',
                'nama_barang' => 'MADU KALIANDRA',
                'size' => '325',
                'stock' => 0,
                'kategori' => '325ml',
                'stock_akhir' => 32,
                'harga_ecer' => '70000.00',
                'harga_rs' => '58000.00',
                'harga_mkl' => '53000.00',
                'harga_ds' => '50000.00',
            ],
            [
                'kode_barang' => '317',
                'nama_barang' => 'MADU RAMBUTAN',
                'size' => '325',
                'stock' => 0,
                'kategori' => '325ml',
                'stock_akhir' => 16,
                'harga_ecer' => '65000.00',
                'harga_rs' => '55000.00',
                'harga_mkl' => '51000.00',
                'harga_ds' => '48000.00',
            ],
            [
                'kode_barang' => '318',
                'nama_barang' => 'MADU MANGGA',
                'size' => '325',
                'stock' => 0,
                'kategori' => '325ml',
                'stock_akhir' => 30,
                'harga_ecer' => '70000.00',
                'harga_rs' => '58000.00',
                'harga_mkl' => '53000.00',
                'harga_ds' => '50000.00',
            ],
            [
                'kode_barang' => '319',
                'nama_barang' => 'MADU KARET',
                'size' => '325',
                'stock' => 0,
                'kategori' => '325ml',
                'stock_akhir' => 15,
                'harga_ecer' => '63000.00',
                'harga_rs' => '48000.00',
                'harga_mkl' => '44600.00',
                'harga_ds' => '47000.00',
            ],
            [
                'kode_barang' => '320',
                'nama_barang' => 'MADU SONOKELING',
                'size' => '325',
                'stock' => 0,
                'kategori' => '325ml',
                'stock_akhir' => 15,
                'harga_ecer' => '67000.00',
                'harga_rs' => '50000.00',
                'harga_mkl' => '46600.00',
                'harga_ds' => '48000.00',
            ],
            [
                'kode_barang' => '321',
                'nama_barang' => 'MADU KLANCENG LEAVYCEPS',
                'size' => '325',
                'stock' => 0,
                'kategori' => '325ml',
                'stock_akhir' => 16,
                'harga_ecer' => '125000.00',
                'harga_rs' => '110000.00',
                'harga_mkl' => '105000.00',
                'harga_ds' => '105000.00',
            ],
            [
                'kode_barang' => '322',
                'nama_barang' => 'MADU KLANCENG ITAMA',
                'size' => '325',
                'stock' => 0,
                'kategori' => '325ml',
                'stock_akhir' => 13,
                'harga_ecer' => '110000.00',
                'harga_rs' => '100000.00',
                'harga_mkl' => '110000.00',
                'harga_ds' => '95000.00',
            ],
            [
                'kode_barang' => '323',
                'nama_barang' => 'MADU KLANCENG BIROI',
                'size' => '325',
                'stock' => 0,
                'kategori' => '325ml',
                'stock_akhir' => 12,
                'harga_ecer' => '120000.00',
                'harga_rs' => '110000.00',
                'harga_mkl' => '95000.00',
                'harga_ds' => '100000.00',
            ],
            [
                'kode_barang' => '324',
                'nama_barang' => 'MADU KLANCENG BAMBU',
                'size' => '325',
                'stock' => 0,
                'kategori' => '325ml',
                'stock_akhir' => 24,
                'harga_ecer' => '95000.00',
                'harga_rs' => '95000.00',
                'harga_mkl' => '80000.00',
                'harga_ds' => '90000.00',
            ],
            [
                'kode_barang' => '325',
                'nama_barang' => 'MADU KLANCENG MAUNI',
                'size' => '325',
                'stock' => 0,
                'kategori' => '325ml',
                'stock_akhir' => 1,
                'harga_ecer' => '100000.00',
                'harga_rs' => '90000.00',
                'harga_mkl' => '85000.00',
                'harga_ds' => '85000.00',
            ],
            [
                'kode_barang' => '326',
                'nama_barang' => 'MADU PAHIT MAHONI',
                'size' => '325',
                'stock' => 0,
                'kategori' => '325ml',
                'stock_akhir' => 15,
                'harga_ecer' => '65000.00',
                'harga_rs' => '50000.00',
                'harga_mkl' => '45000.00',
                'harga_ds' => '47000.00',
            ],
            [
                'kode_barang' => '327',
                'nama_barang' => 'MADU PAHIT JAMBI',
                'size' => '325',
                'stock' => 0,
                'kategori' => '325ml',
                'stock_akhir' => 32,
                'harga_ecer' => '7000.00',
                'harga_rs' => '52500.00',
                'harga_mkl' => '55000.00',
                'harga_ds' => '50000.00',
            ],
            [
                'kode_barang' => '411',
                'nama_barang' => 'MADU MULTIFLORA',
                'size' => '125',
                'stock' => 0,
                'kategori' => '125ml',
                'stock_akhir' => 23,
                'harga_ecer' => '24000.00',
                'harga_rs' => '21000.00',
                'harga_mkl' => '18000.00',
                'harga_ds' => '18000.00',
            ],
            [
                'kode_barang' => '412',
                'nama_barang' => 'MADU RANDU',
                'size' => '125',
                'stock' => 0,
                'kategori' => '125ml',
                'stock_akhir' => 42,
                'harga_ecer' => '35000.00',
                'harga_rs' => '24000.00',
                'harga_mkl' => '24000.00',
                'harga_ds' => '27000.00',
            ],
            [
                'kode_barang' => '413',
                'nama_barang' => 'MADU KOPI',
                'size' => '125',
                'stock' => 0,
                'kategori' => '125ml',
                'stock_akhir' => 23,
                'harga_ecer' => '30000.00',
                'harga_rs' => '25000.00',
                'harga_mkl' => '22000.00',
                'harga_ds' => '23000.00',
            ],
            [
                'kode_barang' => '414',
                'nama_barang' => 'MADU DURIAN',
                'size' => '125',
                'stock' => 0,
                'kategori' => '125ml',
                'stock_akhir' => 13,
                'harga_ecer' => '31000.00',
                'harga_rs' => '27000.00',
                'harga_mkl' => '21000.00',
                'harga_ds' => '24000.00',
            ],
            [
                'kode_barang' => '415',
                'nama_barang' => 'MADU KELENGKENG',
                'size' => '125',
                'stock' => 0,
                'kategori' => '125ml',
                'stock_akhir' => 20,
                'harga_ecer' => '32000.00',
                'harga_rs' => '29000.00',
                'harga_mkl' => '25000.00',
                'harga_ds' => '24000.00',
            ],
            [
                '416',
                'nama_barang' => 'MADU KALIANDRA',
                'size' => '125',
                'stock' => 0,
                'kategori' => '125ml',
                'stock_akhir' => 38,
                'harga_ecer' => '34000.00',
                'harga_rs' => '31000.00',
                'harga_mkl' => '27000.00',
                'harga_ds' => '26000.00',
            ],
            [
                'kode_barang' => '417',
                'nama_barang' => 'MADU RAMBUTAN',
                'size' => '125',
                'stock' => 0,
                'kategori' => '125ml',
                'stock_akhir' => 10,
                'harga_ecer' => '32000.00',
                'harga_rs' => '29000.00',
                'harga_mkl' => '29000.00',
                'harga_ds' => '24000.00',
            ],
            [
                'kode_barang' => '418',
                'nama_barang' => 'MADU MANGGA',
                'size' => '125',
                'stock' => 0,
                'kategori' => '125ml',
                'stock_akhir' => 17,
                'harga_ecer' => '34000.00',
                'harga_rs' => '31000.00',
                'harga_mkl' => '31000.00',
                'harga_ds' => '26000.00',
            ],
            [
                'kode_barang' => '419',
                'nama_barang' => 'MADU KARET',
                'size' => '125',
                'stock' => 0,
                'kategori' => '125ml',
                'stock_akhir' => 8,
                'harga_ecer' => '28000.00',
                'harga_rs' => '24000.00',
                'harga_mkl' => '21000.00',
                'harga_ds' => '22000.00',
            ],
            [
                'kode_barang' => '420',
                'nama_barang' => 'MADU SONOKELING',
                'size' => '125',
                'stock' => 0,
                'kategori' => '125ml',
                'stock_akhir' => 9,
                'harga_ecer' => '37000.00',
                'harga_rs' => '25000.00',
                'harga_mkl' => '22000.00',
                'harga_ds' => '23000.00',
            ],
            [
                'kode_barang' => '421',
                'nama_barang' => 'MADU HUTAN LIAR',
                'size' => '125',
                'stock' => 0,
                'kategori' => '125ml',
                'stock_akhir' => 25,
                'harga_ecer' => '37000.00',
                'harga_rs' => '30000.00',
                'harga_mkl' => '28000.00',
                'harga_ds' => '29000.00',
            ],
            [
                'kode_barang' => '422',
                'nama_barang' => 'MADU HUTAN GUNG',
                'size' => '125',
                'stock' => 0,
                'kategori' => '125ml',
                'stock_akhir' => 11,
                'harga_ecer' => '41000.00',
                'harga_rs' => '32000.00',
                'harga_mkl' => '30000.00',
                'harga_ds' => '31000.00',
            ],
            [
                'kode_barang' => '423',
                'nama_barang' => 'MADU JAMBI',
                'size' => '125',
                'stock' => 0,
                'kategori' => '125ml',
                'stock_akhir' => 10,
                'harga_ecer' => '34000.00',
                'harga_rs' => '24000.00',
                'harga_mkl' => '22000.00',
                'harga_ds' => '26000.00',
            ],
            [
                'kode_barang' => '424',
                'nama_barang' => 'MADU SUMATERA',
                'size' => '125',
                'stock' => 0,
                'kategori' => '125ml',
                'stock_akhir' => 14,
                'harga_ecer' => '34000.00',
                'harga_rs' => '24000.00',
                'harga_mkl' => '22000.00',
                'harga_ds' => '26000.00',
            ],
            [
                'kode_barang' => '425',
                'nama_barang' => 'MADU RIAU',
                'size' => '125',
                'stock' => 0,
                'kategori' => '125ml',
                'stock_akhir' => 3,
                'harga_ecer' => '36000.00',
                'harga_rs' => '26000.00',
                'harga_mkl' => '24000.00',
                'harga_ds' => '28000.00',
            ],
            [
                'kode_barang' => '426',
                'nama_barang' => 'MADU BANGKA',
                'size' => '125',
                'stock' => 0,
                'kategori' => '125ml',
                'stock_akhir' => 14,
                'harga_ecer' => '36000.00',
                'harga_rs' => '26000.00',
                'harga_mkl' => '24000.00',
                'harga_ds' => '28000.00',
            ],
            [
                'kode_barang' => '427',
                'nama_barang' => 'MADU FLORES',
                'size' => '125',
                'stock' => 0,
                'kategori' => '',
                'stock_akhir' => 21,
                'harga_ecer' => '38000.00',
                'harga_rs' => '28000.00',
                'harga_mkl' => '28000.00',
                'harga_ds' => '30000.00',
            ],
            [
                'kode_barang' => '428',
                'nama_barang' => 'MADU SUMBAWA',
                'size' => '125',
                'stock' => 0,
                'kategori' => '125ml',
                'stock_akhir' => 18,
                'harga_ecer' => '38000.00',
                'harga_rs' => '28000.00',
                'harga_mkl' => '28000.00',
                'harga_ds' => '30000.00',
            ],
            [
                'kode_barang' => '429',
                'nama_barang' => 'MADU AKASIA',
                'size' => '125',
                'stock' => 0,
                'kategori' => '125ml',
                'stock_akhir' => 16,
                'harga_ecer' => '35000.00',
                'harga_rs' => '28000.00',
                'harga_mkl' => '30000.00',
                'harga_ds' => '28000.00',
            ],
            [
                'kode_barang' => '611',
                'nama_barang' => 'BAWANG LANANG',
                'size' => '210g',
                'stock' => 0,
                'kategori' => '210g',
                'stock_akhir' => 6,
                'harga_ecer' => '35000.00',
                'harga_rs' => '35000.00',
                'harga_mkl' => '35000.00',
                'harga_ds' => '35000.00',
            ],
            [
                'kode_barang' => '612',
                'nama_barang' => 'BAWANG LANANG',
                'size' => '535g',
                'stock' => 0,
                'kategori' => '535g',
                'stock_akhir' => 0,
                'harga_ecer' => '0.00',
                'harga_rs' => '0.00',
                'harga_mkl' => '0.00',
                'harga_ds' => '0.00',
            ],
            [
                'kode_barang' => '613',
                'nama_barang' => 'SUPERB HONEY',
                'size' => '350g',
                'stock' => 0,
                'kategori' => '350g',
                'stock_akhir' => 23,
                'harga_ecer' => '0.00',
                'harga_rs' => '0.00',
                'harga_mkl' => '0.00',
                'harga_ds' => '0.00',
            ],
            [
                'kode_barang' => '614',
                'nama_barang' => 'SUPERB HONEY',
                'size' => '800g',
                'stock' => 0,
                'kategori' => '800g',
                'stock_akhir' => 12,
                'harga_ecer' => '0.00',
                'harga_rs' => '0.00',
                'harga_mkl' => '0.00',
                'harga_ds' => '0.00',
            ],
            [
                'kode_barang' => '615',
                'nama_barang' => 'SARANG MADU',
                'size' => '85g',
                'stock' => 0,
                'kategori' => '85g',
                'stock_akhir' => 0,
                'harga_ecer' => '0.00',
                'harga_rs' => '0.00',
                'harga_mkl' => '0.00',
                'harga_ds' => '0.00',
            ],
            [
                'kode_barang' => '616',
                'nama_barang' => 'SARANG MADU',
                'size' => '250g',
                'stock' => 0,
                'kategori' => '250g',
                'stock_akhir' => 49,
                'harga_ecer' => '40000.00',
                'harga_rs' => '31000.00',
                'harga_mkl' => '27000.00',
                'harga_ds' => '30000.00',
            ],
            [
                'kode_barang' => '617',
                'nama_barang' => 'SARANG MADU',
                'size' => '500g',
                'stock' => 0,
                'kategori' => '500g',
                'stock_akhir' => 33,
                'harga_ecer' => '80000.00',
                'harga_rs' => '59000.00',
                'harga_mkl' => '52000.00',
                'harga_ds' => '58000.00',
            ],
            [
                'kode_barang' => '618',
                'nama_barang' => 'FLASH SALE MULTI',
                'size' => 'PCS',
                'stock' => 0,
                'kategori' => 'PCS',
                'stock_akhir' => 18,
                'harga_ecer' => '0.00',
                'harga_rs' => '0.00',
                'harga_mkl' => '0.00',
                'harga_ds' => '0.00',
            ],
            [
                'kode_barang' => '619',
                'nama_barang' => 'FLASH SALE RANDU',
                'size' => 'PCS',
                'stock' => 0,
                'kategori' => 'PCS',
                'stock_akhir' => 43,
                'harga_ecer' => '0.00',
                'harga_rs' => '0.00',
                'harga_mkl' => '0.00',
                'harga_ds' => '0.00',
            ],
            [
                'kode_barang' => '620',
                'nama_barang' => 'FLASH SALE KOPI',
                'size' => 'PCS',
                'stock' => 0,
                'kategori' => 'PCS',
                'stock_akhir' => 27,
                'harga_ecer' => '0.00',
                'harga_rs' => '0.00',
                'harga_mkl' => '0.00',
                'harga_ds' => '0.00',
            ],
            [
                'kode_barang' => '621',
                'nama_barang' => 'FLASH SALE DURIAN',
                'size' => 'PCS',
                'stock' => 0,
                'kategori' => 'PCS',
                'stock_akhir' => 11,
                'harga_ecer' => '0.00',
                'harga_rs' => '0.00',
                'harga_mkl' => '0.00',
                'harga_ds' => '0.00',
            ],
            [
                'kode_barang' => '622',
                'nama_barang' => 'FLASH SALE KELENGKENG',
                'size' => 'PCS',
                'stock' => 0,
                'kategori' => 'PCS',
                'stock_akhir' => 16,
                'harga_ecer' => '0.00',
                'harga_rs' => '0.00',
                'harga_mkl' => '0.00',
                'harga_ds' => '0.00',
            ],
            [
                'kode_barang' => '623',
                'nama_barang' => 'FLASH SALE KALIANDRA',
                'size' => 'PCS',
                'stock' => 0,
                'kategori' => 'PCS',
                'stock_akhir' => 39,
                'harga_ecer' => '0.00',
                'harga_rs' => '0.00',
                'harga_mkl' => '0.00',
                'harga_ds' => '0.00',
            ],
            [
                'kode_barang' => '624',
                'nama_barang' => 'FLASH SALE RAMBUTAN',
                'size' => 'PCS',
                'stock' => 0,
                'kategori' => 'PCS',
                'stock_akhir' => 19,
                'harga_ecer' => '0.00',
                'harga_rs' => '0.00',
                'harga_mkl' => '0.00',
                'harga_ds' => '0.00',
            ],
            [
                'kode_barang' => '625',
                'nama_barang' => 'FLASH SALE MANGGA',
                'size' => 'PCS',
                'stock' => 0,
                'kategori' => 'PCS',
                'stock_akhir' => 24,
                'harga_ecer' => '0.00',
                'harga_rs' => '0.00',
                'harga_mkl' => '0.00',
                'harga_ds' => '0.00',
            ],
            [
                'kode_barang' => '626',
                'nama_barang' => 'FLASH SALE KARET',
                'size' => 'PCS',
                'stock' => 0,
                'kategori' => 'PCS',
                'stock_akhir' => 7,
                'harga_ecer' => '0.00',
                'harga_rs' => '0.00',
                'harga_mkl' => '0.00',
                'harga_ds' => '0.00',
            ],
            [
                'kode_barang' => '627',
                'nama_barang' => 'FLASH SALE SONOKELING',
                'size' => 'PCS',
                'stock' => 0,
                'kategori' => 'PCS',
                'stock_akhir' => 16,
                'harga_ecer' => '0.00',
                'harga_rs' => '0.00',
                'harga_mkl' => '0.00',
                'harga_ds' => '0.00',
            ],
            [
                'kode_barang' => '628',
                'nama_barang' => 'FLASH SALE HUTAN LIAR',
                'size' => 'PCS',
                'stock' => 0,
                'kategori' => 'PCS',
                'stock_akhir' => 16,
                'harga_ecer' => '0.00',
                'harga_rs' => '0.00',
                'harga_mkl' => '0.00',
                'harga_ds' => '0.00',
            ],
            [
                'kode_barang' => '629',
                'nama_barang' => 'FLASH SALE HUTAN GUNG',
                'size' => 'PCS',
                'stock' => 0,
                'kategori' => 'PCS',
                'stock_akhir' => 15,
                'harga_ecer' => '0.00',
                'harga_rs' => '0.00',
                'harga_mkl' => '0.00',
                'harga_ds' => '0.00',
            ],
            [
                'kode_barang' => '630',
                'nama_barang' => 'FLASH SALE JAMBI',
                'size' => 'PCS',
                'stock' => 0,
                'kategori' => 'PCS',
                'stock_akhir' => 16,
                'harga_ecer' => '0.00',
                'harga_rs' => '0.00',
                'harga_mkl' => '0.00',
                'harga_ds' => '0.00',
            ],
            [
                'kode_barang' => '631',
                'nama_barang' => 'FLASH SALE SUMATERA',
                'size' => 'PCS',
                'stock' => 0,
                'kategori' => 'PCS',
                'stock_akhir' => 6,
                'harga_ecer' => '0.00',
                'harga_rs' => '0.00',
                'harga_mkl' => '0.00',
                'harga_ds' => '0.00',
            ],
            [
                'kode_barang' => '632',
                'nama_barang' => 'FLASH SALE RIAU',
                'size' => 'PCS',
                'stock' => 0,
                'kategori' => 'PCS',
                'stock_akhir' => 7,
                'harga_ecer' => '0.00',
                'harga_rs' => '0.00',
                'harga_mkl' => '0.00',
                'harga_ds' => '0.00',
            ],
            [
                'kode_barang' => '633',
                'nama_barang' => 'FLASH SALE BANGKA',
                'size' => 'PCS',
                'stock' => 0,
                'kategori' => 'PCS',
                'stock_akhir' => 9,
                'harga_ecer' => '0.00',
                'harga_rs' => '0.00',
                'harga_mkl' => '0.00',
                'harga_ds' => '0.00',
            ],
            [
                'kode_barang' => '634',
                'nama_barang' => 'FLASH SALE FLORES',
                'size' => 'PCS',
                'stock' => 0,
                'kategori' => 'PCS',
                'stock_akhir' => 13,
                'harga_ecer' => '0.00',
                'harga_rs' => '0.00',
                'harga_mkl' => '0.00',
                'harga_ds' => '0.00',
            ],
            [
                'kode_barang' => '635',
                'nama_barang' => 'FLASH SALE SUMBAWA',
                'size' => 'PCS',
                'stock' => 0,
                'kategori' => 'PCS',
                'stock_akhir' => 32,
                'harga_ecer' => '0.00',
                'harga_rs' => '0.00',
                'harga_mkl' => '0.00',
                'harga_ds' => '0.00',
            ],
            [
                'kode_barang' => '636',
                'nama_barang' => 'FLASH SALE AKASIA',
                'size' => 'PCS',
                'stock' => 0,
                'kategori' => 'PCS',
                'stock_akhir' => 23,
                'harga_ecer' => '0.00',
                'harga_rs' => '0.00',
                'harga_mkl' => '0.00',
                'harga_ds' => '0.00',
            ],
            [
                'kode_barang' => '637',
                'nama_barang' => 'FLASH SALE K.LEAVY',
                'size' => 'PCS',
                'stock' => 0,
                'kategori' => 'PCS',
                'stock_akhir' => 18,
                'harga_ecer' => '0.00',
                'harga_rs' => '0.00',
                'harga_mkl' => '0.00',
                'harga_ds' => '0.00',
            ],
            [
                'kode_barang' => '638',
                'nama_barang' => 'FLASH SALE K.ITAMA',
                'size' => 'PCS',
                'stock' => 0,
                'kategori' => 'PCS',
                'stock_akhir' => 13,
                'harga_ecer' => '0.00',
                'harga_rs' => '0.00',
                'harga_mkl' => '0.00',
                'harga_ds' => '0.00',
            ],
            [
                'kode_barang' => '639',
                'nama_barang' => 'FLASH SALE K.BIROI',
                'size' => 'PCS',
                'stock' => 0,
                'kategori' => 'PCS',
                'stock_akhir' => 7,
                'harga_ecer' => '0.00',
                'harga_rs' => '0.00',
                'harga_mkl' => '0.00',
                'harga_ds' => '0.00',
            ],
            [
                'kode_barang' => '640',
                'nama_barang' => 'FLASH SALE K.BAMBU',
                'size' => 'PCS',
                'stock' => 0,
                'kategori' => 'PCS',
                'stock_akhir' => 14,
                'harga_ecer' => '0.00',
                'harga_rs' => '0.00',
                'harga_mkl' => '0.00',
                'harga_ds' => '0.00',
            ],
            [
                'kode_barang' => '641',
                'nama_barang' => 'FLASH SALE K.MAUNI',
                'size' => 'PCS',
                'stock' => 0,
                'kategori' => 'PCS',
                'stock_akhir' => 13,
                'harga_ecer' => '0.00',
                'harga_rs' => '0.00',
                'harga_mkl' => '0.00',
                'harga_ds' => '0.00',
            ],
            [
                'kode_barang' => '642',
                'nama_barang' => 'FLASH SALE PAHIT MAHONI',
                'size' => 'PCS',
                'stock' => 0,
                'kategori' => 'PCS',
                'stock_akhir' => 17,
                'harga_ecer' => '0.00',
                'harga_rs' => '0.00',
                'harga_mkl' => '0.00',
                'harga_ds' => '0.00',
            ],
            [
                'kode_barang' => '643',
                'nama_barang' => 'FLASH SALE PAHIT JAMBI',
                'size' => 'PCS',
                'stock' => 0,
                'kategori' => 'PCS',
                'stock_akhir' => 15,
                'harga_ecer' => '0.00',
                'harga_rs' => '0.00',
                'harga_mkl' => '0.00',
                'harga_ds' => '0.00',
            ],
            [
                'kode_barang' => '644',
                'nama_barang' => 'FLASH SALE BAWANG LANANG',
                'size' => 'PCS',
                'stock' => 0,
                'kategori' => 'PCS',
                'stock_akhir' => 11,
                'harga_ecer' => '0.00',
                'harga_rs' => '0.00',
                'harga_mkl' => '0.00',
                'harga_ds' => '0.00',
            ],
            [
                'kode_barang' => '645',
                'nama_barang' => 'FLASH SALE JABU',
                'size' => 'PCS',
                'stock' => 0,
                'kategori' => 'PCS',
                'stock_akhir' => 0,
                'harga_ecer' => '0.00',
                'harga_rs' => '0.00',
                'harga_mkl' => '0.00',
                'harga_ds' => '0.00',
            ],
            [
                'kode_barang' => '646',
                'nama_barang' => 'FLASH SALE KALAYA',
                'size' => 'PCS',
                'stock' => 0,
                'kategori' => 'PCS',
                'stock_akhir' => 0,
                'harga_ecer' => '0.00',
                'harga_rs' => '0.00',
                'harga_mkl' => '0.00',
                'harga_ds' => '0.00',
            ],
            [
                'kode_barang' => '647',
                'nama_barang' => 'WEDANG UWUH',
                'size' => 'PCS',
                'stock' => 0,
                'kategori' => 'PCS',
                'stock_akhir' => 85,
                'harga_ecer' => '0.00',
                'harga_rs' => '0.00',
                'harga_mkl' => '0.00',
                'harga_ds' => '0.00',
            ],
            [
                'kode_barang' => '648',
                'nama_barang' => 'HIMALAYA SALT',
                'size' => '10GR',
                'stock' => 0,
                'kategori' => '10GR',
                'stock_akhir' => 0,
                'harga_ecer' => '0.00',
                'harga_rs' => '0.00',
                'harga_mkl' => '0.00',
                'harga_ds' => '0.00',
            ],
            [
                'kode_barang' => '649',
                'nama_barang' => 'HIMALAYA SALT',
                'size' => '100 G',
                'stock' => 0,
                'kategori' => '100G',
                'stock_akhir' => 5,
                'harga_ecer' => '0.00',
                'harga_rs' => '0.00',
                'harga_mkl' => '0.00',
                'harga_ds' => '0.00',
            ],
            [
                'kode_barang' => '650',
                'nama_barang' => 'HIMALAYA SALT',
                'size' => '250 G',
                'stock' => 0,
                'kategori' => '250G',
                'stock_akhir' => 4,
                'harga_ecer' => '0.00',
                'harga_rs' => '0.00',
                'harga_mkl' => '0.00',
                'harga_ds' => '0.00',
            ],
            [
                'kode_barang' => '651',
                'nama_barang' => 'CHIA SEED',
                'size' => '10GR',
                'stock' => 0,
                'kategori' => '10GR',
                'stock_akhir' => 0,
                'harga_ecer' => '0.00',
                'harga_rs' => '0.00',
                'harga_mkl' => '0.00',
                'harga_ds' => '0.00',
            ],
            [
                'kode_barang' => '652',
                'nama_barang' => 'CHIA SEED',
                'size' => '100GR',
                'stock' => 0,
                'kategori' => '100GR',
                'stock_akhir' => 0,
                'harga_ecer' => '0.00',
                'harga_rs' => '0.00',
                'harga_mkl' => '0.00',
                'harga_ds' => '0.00',
            ],
            [
                'kode_barang' => '653',
                'nama_barang' => 'HABBATUSAUDA',
                'size' => 'PCS',
                'stock' => 0,
                'kategori' => 'PCS',
                'stock_akhir' => 1,
                'harga_ecer' => '0.00',
                'harga_rs' => '0.00',
                'harga_mkl' => '0.00',
                'harga_ds' => '0.00',
            ],
            [
                'kode_barang' => '654',
                'nama_barang' => 'BEEPOLLEN MULTI',
                'size' => 'PCS',
                'stock' => 0,
                'kategori' => 'PCS',
                'stock_akhir' => 0,
                'harga_ecer' => '0.00',
                'harga_rs' => '0.00',
                'harga_mkl' => '0.00',
                'harga_ds' => '0.00',
            ],
            [
                'kode_barang' => '655',
                'nama_barang' => 'BEEPOLLEN JAGUNG',
                'size' => 'PCS',
                'stock' => 0,
                'kategori' => 'PCS',
                'stock_akhir' => 7,
                'harga_ecer' => '0.00',
                'harga_rs' => '0.00',
                'harga_mkl' => '0.00',
                'harga_ds' => '0.00',
            ],
            [
                'kode_barang' => '656',
                'nama_barang' => 'YAMAN',
                'size' => 'PCS',
                'stock' => 0,
                'kategori' => 'PCS',
                'stock_akhir' => 0,
                'harga_ecer' => '0.00',
                'harga_rs' => '0.00',
                'harga_mkl' => '0.00',
                'harga_ds' => '0.00',
            ],
            [
                'kode_barang' => '657',
                'nama_barang' => 'YAMAN',
                'size' => 'PCS',
                'stock' => 0,
                'kategori' => 'PCS',
                'stock_akhir' => 0,
                'harga_ecer' => '0.00',
                'harga_rs' => '0.00',
                'harga_mkl' => '0.00',
                'harga_ds' => '0.00',
            ],
            [
                'kode_barang' => '658',
                'nama_barang' => 'ZURIAT',
                'size' => '50GR',
                'stock' => 0,
                'kategori' => '50GR',
                'stock_akhir' => 10,
                'harga_ecer' => '0.00',
                'harga_rs' => '0.00',
                'harga_mkl' => '0.00',
                'harga_ds' => '0.00',
            ],
            [
                'kode_barang' => '659',
                'nama_barang' => 'ZURIAT',
                'size' => '100GR',
                'stock' => 0,
                'kategori' => '100GR',
                'stock_akhir' => 2,
                'harga_ecer' => '0.00',
                'harga_rs' => '0.00',
                'harga_mkl' => '0.00',
                'harga_ds' => '0.00',
            ],
            [
                'kode_barang' => '660',
                'nama_barang' => 'PROPOLIS',
                'size' => 'PCS',
                'stock' => 0,
                'kategori' => 'PCS',
                'stock_akhir' => 13,
                'harga_ecer' => '0.00',
                'harga_rs' => '0.00',
                'harga_mkl' => '0.00',
                'harga_ds' => '0.00',
            ],
            [
                'kode_barang' => '661',
                'nama_barang' => 'BIOSUKHE 8 BENING',
                'size' => 'PCS',
                'stock' => 0,
                'kategori' => 'PCS',
                'stock_akhir' => 10,
                'harga_ecer' => '0.00',
                'harga_rs' => '0.00',
                'harga_mkl' => '0.00',
                'harga_ds' => '0.00',
            ],
            [
                'kode_barang' => '662',
                'nama_barang' => 'BIOSUKHE 8 PEKAT',
                'size' => 'PCS',
                'stock' => 0,
                'kategori' => 'PCS',
                'stock_akhir' => 7,
                'harga_ecer' => '0.00',
                'harga_rs' => '0.00',
                'harga_mkl' => '0.00',
                'harga_ds' => '0.00',
            ],
            [
                'kode_barang' => '663',
                'nama_barang' => 'BIOSUKHE 10',
                'size' => 'PCS',
                'stock' => 0,
                'kategori' => 'PCS',
                'stock_akhir' => 3,
                'harga_ecer' => '0.00',
                'harga_rs' => '0.00',
                'harga_mkl' => '0.00',
                'harga_ds' => '0.00',
            ],
            [
                'kode_barang' => '664',
                'nama_barang' => 'BIOSUKHE 12',
                'size' => 'PCS',
                'stock' => 0,
                'kategori' => 'PCS',
                'stock_akhir' => 9,
                'harga_ecer' => '0.00',
                'harga_rs' => '0.00',
                'harga_mkl' => '0.00',
                'harga_ds' => '0.00',
            ],
            [
                'kode_barang' => '665',
                'nama_barang' => 'BIOSUKHE 14',
                'size' => 'PCS',
                'stock' => 0,
                'kategori' => 'PCS',
                'stock_akhir' => 3,
                'harga_ecer' => '0.00',
                'harga_rs' => '0.00',
                'harga_mkl' => '0.00',
                'harga_ds' => '0.00',
            ],
            [
                'kode_barang' => '666',
                'nama_barang' => 'BIOSUKHE 18',
                'size' => 'PCS',
                'stock' => 0,
                'kategori' => 'PCS',
                'stock_akhir' => 5,
                'harga_ecer' => '0.00',
                'harga_rs' => '0.00',
                'harga_mkl' => '0.00',
                'harga_ds' => '0.00',
            ],
            [
                'kode_barang' => '667',
                'nama_barang' => 'MINYAK KUTUS KUTUS',
                'size' => 'PCS',
                'stock' => 0,
                'kategori' => 'PCS',
                'stock_akhir' => 3,
                'harga_ecer' => '0.00',
                'harga_rs' => '0.00',
                'harga_mkl' => '0.00',
                'harga_ds' => '0.00',
            ],
            [
                'kode_barang' => '668',
                'nama_barang' => 'KACA 100 MULTI',
                'size' => '100GR',
                'stock' => 0,
                'kategori' => '100GR',
                'stock_akhir' => 2,
                'harga_ecer' => '0.00',
                'harga_rs' => '0.00',
                'harga_mkl' => '0.00',
                'harga_ds' => '0.00',
            ],
            [
                'kode_barang' => '669',
                'nama_barang' => 'KACA 100 RANDU',
                'size' => '100GR',
                'stock' => 0,
                'kategori' => '100GR',
                'stock_akhir' => 0,
                'harga_ecer' => '0.00',
                'harga_rs' => '0.00',
                'harga_mkl' => '0.00',
                'harga_ds' => '0.00',
            ],
            [
                'kode_barang' => '670',
                'nama_barang' => 'KACA 100 KELENGKENG',
                'size' => '100GR',
                'stock' => 0,
                'kategori' => '100GR',
                'stock_akhir' => 2,
                'harga_ecer' => '0.00',
                'harga_rs' => '0.00',
                'harga_mkl' => '0.00',
                'harga_ds' => '0.00',
            ],
            [
                'kode_barang' => '671',
                'nama_barang' => 'KACA 100 KALIANDRA',
                'size' => '100GR',
                'stock' => 0,
                'kategori' => '100GR',
                'stock_akhir' => 0,
                'harga_ecer' => '0.00',
                'harga_rs' => '0.00',
                'harga_mkl' => '0.00',
                'harga_ds' => '0.00',
            ],
            [
                'kode_barang' => '672',
                'nama_barang' => 'MP MULTIFLORA',
                'size' => '350GR',
                'stock' => 0,
                'kategori' => '350GR',
                'stock_akhir' => 0,
                'harga_ecer' => '0.00',
                'harga_rs' => '0.00',
                'harga_mkl' => '0.00',
                'harga_ds' => '0.00',
            ],
            [
                'kode_barang' => '673',
                'nama_barang' => 'MP RANDU',
                'size' => '350GR',
                'stock' => 0,
                'kategori' => '350GR',
                'stock_akhir' => 0,
                'harga_ecer' => '0.00',
                'harga_rs' => '0.00',
                'harga_mkl' => '0.00',
                'harga_ds' => '0.00',
            ],
            [
                'kode_barang' => '674',
                'nama_barang' => 'MP KALIANDRA',
                'size' => '350GR',
                'stock' => 0,
                'kategori' => '350GR',
                'stock_akhir' => 0,
                'harga_ecer' => '0.00',
                'harga_rs' => '0.00',
                'harga_mkl' => '0.00',
                'harga_ds' => '0.00',
            ],
            [
                'kode_barang' => '675',
                'nama_barang' => 'MP KLANCENG',
                'size' => '350GR',
                'stock' => 0,
                'kategori' => '350GR',
                'stock_akhir' => 0,
                'harga_ecer' => '0.00',
                'harga_rs' => '0.00',
                'harga_mkl' => '0.00',
                'harga_ds' => '0.00',
            ],
            [
                'kode_barang' => '676',
                'nama_barang' => 'MP KOPI',
                'size' => '350GR',
                'stock' => 0,
                'kategori' => '350GR',
                'stock_akhir' => 0,
                'harga_ecer' => '0.00',
                'harga_rs' => '0.00',
                'harga_mkl' => '0.00',
                'harga_ds' => '0.00',
            ],
            [
                'kode_barang' => '677',
                'nama_barang' => 'MP HUTAN LIAR',
                'size' => '350GR',
                'stock' => 0,
                'kategori' => '350GR',
                'stock_akhir' => 0,
                'harga_ecer' => '0.00',
                'harga_rs' => '0.00',
                'harga_mkl' => '0.00',
                'harga_ds' => '0.00',
            ],
            [
                'kode_barang' => '678',
                'nama_barang' => 'MP KELENGKENG',
                'size' => '350GR',
                'stock' => 0,
                'kategori' => '350GR',
                'stock_akhir' => 1,
                'harga_ecer' => '0.00',
                'harga_rs' => '0.00',
                'harga_mkl' => '0.00',
                'harga_ds' => '0.00',
            ],
            [
                'kode_barang' => '679',
                'nama_barang' => 'FITMTY',
                'size' => 'PCS',
                'stock' => 0,
                'kategori' => '350GR',
                'stock_akhir' => 10,
                'harga_ecer' => '0.00',
                'harga_rs' => '0.00',
                'harga_mkl' => '0.00',
                'harga_ds' => '0.00',
            ],
            [
                'kode_barang' => '680',
                'nama_barang' => 'TESPEK',
                'size' => 'PCS',
                'stock' => 0,
                'kategori' => '350GR',
                'stock_akhir' => 53,
                'harga_ecer' => '0.00',
                'harga_rs' => '0.00',
                'harga_mkl' => '0.00',
                'harga_ds' => '0.00',
            ],
            [
                'kode_barang' => '681',
                'nama_barang' => 'INTERMIE',
                'size' => 'PCS',
                'stock' => 0,
                'kategori' => '350GR',
                'stock_akhir' => 5,
                'harga_ecer' => '0.00',
                'harga_rs' => '0.00',
                'harga_mkl' => '0.00',
                'harga_ds' => '0.00',
            ],
            [
                'kode_barang' => '682',
                'nama_barang' => 'INDOMIE',
                'size' => 'PCS',
                'stock' => 0,
                'kategori' => '350GR',
                'stock_akhir' => 15,
                'harga_ecer' => '0.00',
                'harga_rs' => '0.00',
                'harga_mkl' => '0.00',
                'harga_ds' => '0.00',
            ],
            [
                'kode_barang' => '683',
                'nama_barang' => 'ROYYAL JELLY',
                'size' => 'PCS',
                'stock' => 0,
                'kategori' => '350GR',
                'stock_akhir' => 9,
                'harga_ecer' => '0.00',
                'harga_rs' => '0.00',
                'harga_mkl' => '0.00',
                'harga_ds' => '0.00',
            ],
            [
                'kode_barang' => '684',
                'nama_barang' => 'SAFRON',
                'size' => '15ML',
                'stock' => 0,
                'kategori' => '350GR',
                'stock_akhir' => 15,
                'harga_ecer' => '0.00',
                'harga_rs' => '0.00',
                'harga_mkl' => '0.00',
                'harga_ds' => '0.00',
            ],
            [
                'kode_barang' => '685',
                'nama_barang' => 'BASE HONEY',
                'size' => '1KG',
                'stock' => 0,
                'kategori' => '350GR',
                'stock_akhir' => 0,
                'harga_ecer' => '0.00',
                'harga_rs' => '0.00',
                'harga_mkl' => '0.00',
                'harga_ds' => '0.00',
            ],
            [
                'kode_barang' => '686',
                'nama_barang' => 'BASE HONEY',
                'size' => '500ML',
                'stock' => 0,
                'kategori' => '350GR',
                'stock_akhir' => 1,
                'harga_ecer' => '0.00',
                'harga_rs' => '0.00',
                'harga_mkl' => '0.00',
                'harga_ds' => '0.00',
            ],
            [
                'kode_barang' => '687',
                'nama_barang' => 'BASE HONEY',
                'size' => '325ML',
                'stock' => 0,
                'kategori' => '350GR',
                'stock_akhir' => 0,
                'harga_ecer' => '0.00',
                'harga_rs' => '0.00',
                'harga_mkl' => '0.00',
                'harga_ds' => '0.00',
            ],
            [
                'kode_barang' => '688',
                'nama_barang' => 'BASE HONEY',
                'size' => '125ML',
                'stock' => 0,
                'kategori' => '350GR',
                'stock_akhir' => 0,
                'harga_ecer' => '0.00',
                'harga_rs' => '0.00',
                'harga_mkl' => '0.00',
                'harga_ds' => '0.00',
            ],
            [
                'kode_barang' => '689',
                'nama_barang' => 'BASE HONEY',
                'size' => '5kg',
                'stock' => 0,
                'kategori' => '350GR',
                'stock_akhir' => 0,
                'harga_ecer' => '0.00',
                'harga_rs' => '0.00',
                'harga_mkl' => '0.00',
                'harga_ds' => '0.00',
            ],
            [
                'kode_barang' => '690',
                'nama_barang' => 'MULTI EKSLUSIF',
                'size' => '100gr',
                'stock' => 0,
                'kategori' => '100gr',
                'stock_akhir' => 20,
                'harga_ecer' => '0.00',
                'harga_rs' => '0.00',
                'harga_mkl' => '0.00',
                'harga_ds' => '0.00',
            ],
            [
                'kode_barang' => '691',
                'nama_barang' => 'RANDU EKSLUSIF',
                'size' => '100gr',
                'stock' => 0,
                'kategori' => '100gr',
                'stock_akhir' => 0,
                'harga_ecer' => '0.00',
                'harga_rs' => '0.00',
                'harga_mkl' => '0.00',
                'harga_ds' => '0.00',
            ],
            [
                'kode_barang' => '692',
                'nama_barang' => 'HUTAN LIAR EKSLUSIF',
                'size' => '100gr',
                'stock' => 0,
                'kategori' => '100gr',
                'stock_akhir' => 20,
                'harga_ecer' => '0.00',
                'harga_rs' => '0.00',
                'harga_mkl' => '0.00',
                'harga_ds' => '0.00',
            ],
            [
                'kode_barang' => '693',
                'nama_barang' => 'KELENGKENG EKSLUSIF',
                'size' => '100gr',
                'stock' => 0,
                'kategori' => '100gr',
                'stock_akhir' => 8,
                'harga_ecer' => '0.00',
                'harga_rs' => '0.00',
                'harga_mkl' => '0.00',
                'harga_ds' => '0.00',
            ],
            [
                'kode_barang' => '694',
                'nama_barang' => 'KALIANDRA EKSLUSIF',
                'size' => '100gr',
                'stock' => 0,
                'kategori' => '100gr',
                'stock_akhir' => 1,
                'harga_ecer' => '0.00',
                'harga_rs' => '0.00',
                'harga_mkl' => '0.00',
                'harga_ds' => '0.00',
            ],
            [
                'kode_barang' => '695',
                'nama_barang' => 'MUESLI BESAR ',
                'size' => '1300gr',
                'stock' => 0,
                'kategori' => '1300gr',
                'stock_akhir' => 0,
                'harga_ecer' => '0.00',
                'harga_rs' => '0.00',
                'harga_mkl' => '0.00',
                'harga_ds' => '0.00',
            ],
            [
                'kode_barang' => '696',
                'nama_barang' => 'MUESLI KECIL',
                'size' => '750gr',
                'stock' => 0,
                'kategori' => '750gr',
                'stock_akhir' => 0,
                'harga_ecer' => '0.00',
                'harga_rs' => '0.00',
                'harga_mkl' => '0.00',
                'harga_ds' => '0.00',
            ],
            [
                'kode_barang' => '697',
                'nama_barang' => 'Best Honey 280 oval',
                'size' => 'pcs',
                'stock' => 0,
                'kategori' => 'PCS',
                'stock_akhir' => 0,
                'harga_ecer' => '0.00',
                'harga_rs' => '0.00',
                'harga_mkl' => '0.00',
                'harga_ds' => '0.00',
            ],
            [
                'kode_barang' => '698',
                'nama_barang' => 'Sari Lemon 250',
                'size' => 'pcs',
                'stock' => 0,
                'kategori' => 'PCS',
                'stock_akhir' => 33,
                'harga_ecer' => '0.00',
                'harga_rs' => '0.00',
                'harga_mkl' => '0.00',
                'harga_ds' => '0.00',
            ],
            [
                'kode_barang' => '699',
                'nama_barang' => 'Sari Lemon 500',
                'size' => 'pcs',
                'stock' => 0,
                'kategori' => 'PCS',
                'stock_akhir' => 6,
                'harga_ecer' => '0.00',
                'harga_rs' => '0.00',
                'harga_mkl' => '0.00',
                'harga_ds' => '0.00',
            ],
            [
                'kode_barang' => '700',
                'nama_barang' => 'Chia seed 200gr',
                'size' => 'pcs',
                'stock' => 0,
                'kategori' => 'PCS',
                'stock_akhir' => 6,
                'harga_ecer' => '0.00',
                'harga_rs' => '0.00',
                'harga_mkl' => '0.00',
                'harga_ds' => '0.00',
            ],
            [
                'kode_barang' => '701',
                'nama_barang' => '',
                'size' => '',
                'stock' => 0,
                'kategori' => '',
                'stock_akhir' => 0,
                'harga_ecer' => '0.00',
                'harga_rs' => '0.00',
                'harga_mkl' => '0.00',
                'harga_ds' => '0.00',
            ],
            [
                'kode_barang' => '702',
                'nama_barang' => '',
                'size' => '',
                'stock' => 0,
                'kategori' => '',
                'stock_akhir' => 0,
                'harga_ecer' => '0.00',
                'harga_rs' => '0.00',
                'harga_mkl' => '0.00',
                'harga_ds' => '0.00',
            ],
            [
                'kode_barang' => '703',
                'nama_barang' => '',
                'size' => '',
                'stock' => 0,
                'kategori' => '',
                'stock_akhir' => 0,
                'harga_ecer' => '0.00',
                'harga_rs' => '0.00',
                'harga_mkl' => '0.00',
                'harga_ds' => '0.00',
            ],
            [
                'kode_barang' => '704',
                'nama_barang' => '',
                'size' => '',
                'stock' => 0,
                'kategori' => '',
                'stock_akhir' => 0,
                'harga_ecer' => '0.00',
                'harga_rs' => '0.00',
                'harga_mkl' => '0.00',
                'harga_ds' => '0.00',
            ],
            [
                'kode_barang' => '705',
                'nama_barang' => '',
                'size' => '',
                'stock' => 0,
                'kategori' => '',
                'stock_akhir' => 0,
                'harga_ecer' => '0.00',
                'harga_rs' => '0.00',
                'harga_mkl' => '0.00',
                'harga_ds' => '0.00',
            ],
            [
                'kode_barang' => '706',
                'nama_barang' => '',
                'size' => '',
                'stock' => 0,
                'kategori' => '',
                'stock_akhir' => 0,
                'harga_ecer' => '0.00',
                'harga_rs' => '0.00',
                'harga_mkl' => '0.00',
                'harga_ds' => '0.00',
            ],
            [
                'kode_barang' => '707',
                'nama_barang' => '',
                'size' => '',
                'stock' => 0,
                'kategori' => '',
                'stock_akhir' => 0,
                'harga_ecer' => '0.00',
                'harga_rs' => '0.00',
                'harga_mkl' => '0.00',
                'harga_ds' => '0.00',
            ],
            [
                'kode_barang' => '708',
                'nama_barang' => '',
                'size' => '',
                'stock' => 0,
                'kategori' => '',
                'stock_akhir' => 0,
                'harga_ecer' => '0.00',
                'harga_rs' => '0.00',
                'harga_mkl' => '0.00',
                'harga_ds' => '0.00',
            ],
            [
                'kode_barang' => '709',
                'nama_barang' => '',
                'size' => '',
                'stock' => 0,
                'kategori' => '',
                'stock_akhir' => 0,
                'harga_ecer' => '0.00',
                'harga_rs' => '0.00',
                'harga_mkl' => '0.00',
                'harga_ds' => '0.00',
            ],
            [
                'kode_barang' => '710',
                'nama_barang' => '',
                'size' => '',
                'stock' => 0,
                'kategori' => '',
                'stock_akhir' => 0,
                'harga_ecer' => '0.00',
                'harga_rs' => '0.00',
                'harga_mkl' => '0.00',
                'harga_ds' => '0.00',
            ],
            [
                'kode_barang' => '711',
                'nama_barang' => '',
                'size' => '',
                'stock' => 0,
                'kategori' => '',
                'stock_akhir' => 0,
                'harga_ecer' => '0.00',
                'harga_rs' => '0.00',
                'harga_mkl' => '0.00',
                'harga_ds' => '0.00',
            ],
            [
                'kode_barang' => '712',
                'nama_barang' => '',
                'size' => '',
                'stock' => 0,
                'kategori' => '',
                'stock_akhir' => 0,
                'harga_ecer' => '0.00',
                'harga_rs' => '0.00',
                'harga_mkl' => '0.00',
                'harga_ds' => '0.00',
            ],
            [
                'kode_barang' => '713',
                'nama_barang' => '',
                'size' => '',
                'stock' => 0,
                'kategori' => '',
                'stock_akhir' => 0,
                'harga_ecer' => '0.00',
                'harga_rs' => '0.00',
                'harga_mkl' => '0.00',
                'harga_ds' => '0.00',
            ],
            [
                'kode_barang' => '714',
                'nama_barang' => '',
                'size' => '',
                'stock' => 0,
                'kategori' => '',
                'stock_akhir' => 0,
                'harga_ecer' => '0.00',
                'harga_rs' => '0.00',
                'harga_mkl' => '0.00',
                'harga_ds' => '0.00',
            ],
            [
                'kode_barang' => '715',
                'nama_barang' => '',
                'size' => '',
                'stock' => 0,
                'kategori' => '',
                'stock_akhir' => 0,
                'harga_ecer' => '0.00',
                'harga_rs' => '0.00',
                'harga_mkl' => '0.00',
                'harga_ds' => '0.00',
            ],
            [
                'kode_barang' => '716',
                'nama_barang' => '',
                'size' => '',
                'stock' => 0,
                'kategori' => '',
                'stock_akhir' => 0,
                'harga_ecer' => '0.00',
                'harga_rs' => '0.00',
                'harga_mkl' => '0.00',
                'harga_ds' => '0.00',
            ],
            [
                'kode_barang' => '717',
                'nama_barang' => '',
                'size' => '',
                'stock' => 0,
                'kategori' => '',
                'stock_akhir' => 0,
                'harga_ecer' => '0.00',
                'harga_rs' => '0.00',
                'harga_mkl' => '0.00',
                'harga_ds' => '0.00',
            ],
            [
                'kode_barang' => '718',
                'nama_barang' => '',
                'size' => '',
                'stock' => 0,
                'kategori' => '',
                'stock_akhir' => 0,
                'harga_ecer' => '0.00',
                'harga_rs' => '0.00',
                'harga_mkl' => '0.00',
                'harga_ds' => '0.00',
            ],
            [
                'kode_barang' => '719',
                'nama_barang' => '',
                'size' => '',
                'stock' => 0,
                'kategori' => '',
                'stock_akhir' => 0,
                'harga_ecer' => '0.00',
                'harga_rs' => '0.00',
                'harga_mkl' => '0.00',
                'harga_ds' => '0.00',
            ],
            [
                'kode_barang' => '720',
                'nama_barang' => '',
                'size' => '',
                'stock' => 0,
                'kategori' => '',
                'stock_akhir' => 0,
                'harga_ecer' => '0.00',
                'harga_rs' => '0.00',
                'harga_mkl' => '0.00',
                'harga_ds' => '0.00',
            ],
            [
                'kode_barang' => '721',
                'nama_barang' => '',
                'size' => '',
                'stock' => 0,
                'kategori' => '',
                'stock_akhir' => 0,
                'harga_ecer' => '0.00',
                'harga_rs' => '0.00',
                'harga_mkl' => '0.00',
                'harga_ds' => '0.00',
            ],
            [
                'kode_barang' => '722',
                'nama_barang' => '',
                'size' => '',
                'stock' => 0,
                'kategori' => '',
                'stock_akhir' => 0,
                'harga_ecer' => '0.00',
                'harga_rs' => '0.00',
                'harga_mkl' => '0.00',
                'harga_ds' => '0.00',
            ],
            [
                'kode_barang' => '723',
                'nama_barang' => '',
                'size' => '',
                'stock' => 0,
                'kategori' => '',
                'stock_akhir' => 0,
                'harga_ecer' => '0.00',
                'harga_rs' => '0.00',
                'harga_mkl' => '0.00',
                'harga_ds' => '0.00',
            ],
            [
                'kode_barang' => '724',
                'nama_barang' => '',
                'size' => '',
                'stock' => 0,
                'kategori' => '',
                'stock_akhir' => 0,
                'harga_ecer' => '0.00',
                'harga_rs' => '0.00',
                'harga_mkl' => '0.00',
                'harga_ds' => '0.00',
            ],
            [
                'kode_barang' => '725',
                'nama_barang' => '',
                'size' => '',
                'stock' => 0,
                'kategori' => '',
                'stock_akhir' => 0,
                'harga_ecer' => '0.00',
                'harga_rs' => '0.00',
                'harga_mkl' => '0.00',
                'harga_ds' => '0.00',
            ],
            [
                'kode_barang' => '726',
                'nama_barang' => '',
                'size' => '',
                'stock' => 0,
                'kategori' => '',
                'stock_akhir' => 0,
                'harga_ecer' => '0.00',
                'harga_rs' => '0.00',
                'harga_mkl' => '0.00',
                'harga_ds' => '0.00',
            ],
            [
                'kode_barang' => '727',
                'nama_barang' => '',
                'size' => '',
                'stock' => 0,
                'kategori' => '',
                'stock_akhir' => 0,
                'harga_ecer' => '0.00',
                'harga_rs' => '0.00',
                'harga_mkl' => '0.00',
                'harga_ds' => '0.00',
            ],
            [
                'kode_barang' => '728',
                'nama_barang' => '',
                'size' => '',
                'stock' => 0,
                'kategori' => '',
                'stock_akhir' => 0,
                'harga_ecer' => '0.00',
                'harga_rs' => '0.00',
                'harga_mkl' => '0.00',
                'harga_ds' => '0.00',
            ],
            [
                'kode_barang' => '729',
                'nama_barang' => '',
                'size' => '',
                'stock' => 0,
                'kategori' => '',
                'stock_akhir' => 0,
                'harga_ecer' => '0.00',
                'harga_rs' => '0.00',
                'harga_mkl' => '0.00',
                'harga_ds' => '0.00',
            ],
            [
                'kode_barang' => '730',
                'nama_barang' => '',
                'size' => '',
                'stock' => 0,
                'kategori' => '',
                'stock_akhir' => 0,
                'harga_ecer' => '0.00',
                'harga_rs' => '0.00',
                'harga_mkl' => '0.00',
                'harga_ds' => '0.00',
            ],
            [
                'kode_barang' => '731',
                'nama_barang' => '',
                'size' => '',
                'stock' => 0,
                'kategori' => '',
                'stock_akhir' => 0,
                'harga_ecer' => '0.00',
                'harga_rs' => '0.00',
                'harga_mkl' => '0.00',
                'harga_ds' => '0.00',
            ],
            [
                'kode_barang' => '732',
                'nama_barang' => '',
                'size' => '',
                'stock' => 0,
                'kategori' => '',
                'stock_akhir' => 0,
                'harga_ecer' => '0.00',
                'harga_rs' => '0.00',
                'harga_mkl' => '0.00',
                'harga_ds' => '0.00',
            ],
            [
                'kode_barang' => '733',
                'nama_barang' => '',
                'size' => '',
                'stock' => 0,
                'kategori' => '',
                'stock_akhir' => 0,
                'harga_ecer' => '0.00',
                'harga_rs' => '0.00',
                'harga_mkl' => '0.00',
                'harga_ds' => '0.00',
            ],
            [
                'kode_barang' => '734',
                'nama_barang' => '',
                'size' => '',
                'stock' => 0,
                'kategori' => '',
                'stock_akhir' => 0,
                'harga_ecer' => '0.00',
                'harga_rs' => '0.00',
                'harga_mkl' => '0.00',
                'harga_ds' => '0.00',
            ],
            [
                'kode_barang' => '735',
                'nama_barang' => '',
                'size' => '',
                'stock' => 0,
                'kategori' => '',
                'stock_akhir' => 0,
                'harga_ecer' => '0.00',
                'harga_rs' => '0.00',
                'harga_mkl' => '0.00',
                'harga_ds' => '0.00',
            ],
            [
                'kode_barang' => '736',
                'nama_barang' => '',
                'size' => '',
                'stock' => 0,
                'kategori' => '',
                'stock_akhir' => 0,
                'harga_ecer' => '0.00',
                'harga_rs' => '0.00',
                'harga_mkl' => '0.00',
                'harga_ds' => '0.00',
            ],
            [
                'kode_barang' => '737',
                'nama_barang' => '',
                'size' => '',
                'stock' => 0,
                'kategori' => '',
                'stock_akhir' => 0,
                'harga_ecer' => '0.00',
                'harga_rs' => '0.00',
                'harga_mkl' => '0.00',
                'harga_ds' => '0.00',
            ],
            [
                'kode_barang' => '738',
                'nama_barang' => '',
                'size' => '',
                'stock' => 0,
                'kategori' => '',
                'stock_akhir' => 0,
                'harga_ecer' => '0.00',
                'harga_rs' => '0.00',
                'harga_mkl' => '0.00',
                'harga_ds' => '0.00',
            ],
            [
                'kode_barang' => '739',
                'nama_barang' => '',
                'size' => '',
                'stock' => 0,
                'kategori' => '',
                'stock_akhir' => 0,
                'harga_ecer' => '0.00',
                'harga_rs' => '0.00',
                'harga_mkl' => '0.00',
                'harga_ds' => '0.00',
            ],
            [
                'kode_barang' => '740',
                'nama_barang' => '',
                'size' => '',
                'stock' => 0,
                'kategori' => '',
                'stock_akhir' => 0,
                'harga_ecer' => '0.00',
                'harga_rs' => '0.00',
                'harga_mkl' => '0.00',
                'harga_ds' => '0.00',
            ],
            [
                'kode_barang' => '741',
                'nama_barang' => '',
                'size' => '',
                'stock' => 0,
                'kategori' => '',
                'stock_akhir' => 0,
                'harga_ecer' => '0.00',
                'harga_rs' => '0.00',
                'harga_mkl' => '0.00',
                'harga_ds' => '0.00',
            ],
            [
                'kode_barang' => '742',
                'nama_barang' => '',
                'size' => '',
                'stock' => 0,
                'kategori' => '',
                'stock_akhir' => 0,
                'harga_ecer' => '0.00',
                'harga_rs' => '0.00',
                'harga_mkl' => '0.00',
                'harga_ds' => '0.00',
            ],
            [
                'kode_barang' => '743',
                'nama_barang' => 'FITMTY',
                'size' => '',
                'stock' => 0,
                'kategori' => '',
                'stock_akhir' => 0,
                'harga_ecer' => '0.00',
                'harga_rs' => '0.00',
                'harga_mkl' => '0.00',
                'harga_ds' => '0.00',
            ],
            [
                'kode_barang' => '744',
                'nama_barang' => 'TESPEK',
                'size' => '',
                'stock' => 0,
                'kategori' => '',
                'stock_akhir' => 0,
                'harga_ecer' => '0.00',
                'harga_rs' => '0.00',
                'harga_mkl' => '0.00',
                'harga_ds' => '0.00',
            ],
            [
                'kode_barang' => '745',
                'nama_barang' => '',
                'size' => '',
                'stock' => 0,
                'kategori' => '',
                'stock_akhir' => 0,
                'harga_ecer' => '0.00',
                'harga_rs' => '0.00',
                'harga_mkl' => '0.00',
                'harga_ds' => '0.00',
            ],
            [
                'kode_barang' => '746',
                'nama_barang' => '',
                'size' => '',
                'stock' => 0,
                'kategori' => '',
                'stock_akhir' => 0,
                'harga_ecer' => '0.00',
                'harga_rs' => '0.00',
                'harga_mkl' => '0.00',
                'harga_ds' => '0.00',
            ],
            [
                'kode_barang' => '747',
                'nama_barang' => '',
                'size' => '',
                'stock' => 0,
                'kategori' => '',
                'stock_akhir' => 0,
                'harga_ecer' => '0.00',
                'harga_rs' => '0.00',
                'harga_mkl' => '0.00',
                'harga_ds' => '0.00',
            ],
            [
                'kode_barang' => '748',
                'nama_barang' => '',
                'size' => '',
                'stock' => 0,
                'stock_akhir' => 0,
                'kategori' => '',
                'harga_ecer' => '0.00',
                'harga_rs' => '0.00',
                'harga_mkl' => '0.00',
                'harga_ds' => '0.00',
            ],
            [
                'kode_barang' => '749',
                'nama_barang' => '',
                'size' => '',
                'stock' => 0,
                'stock_akhir' => 0,
                'kategori' => '',
                'harga_ecer' => '0.00',
                'harga_rs' => '0.00',
                'harga_mkl' => '0.00',
                'harga_ds' => '0.00',
            ],
        ];

        DB::table('produk_jadis')->insert($data);
    }
}
