import "./bootstrap";
import "flowbite";
import "./mychart.js";
import "./scroll.js";
import "./lineChart.js";
import "./dailyTarget.js";
import "./salesAnalytics.js";
import "./dailyOrderStats.js";
import "./revenue.js";
